export const COLLECTION_REQUEST = 'COLLECTION_REQUEST'
export const COLLECTION_SUCCESS = 'COLLECTION_SUCCESS'
export const COLLECTION_FAIL = 'COLLECTION_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
