import Head from "next/head";
import { useRouter } from "next/router";
import styles from "./User.module.css";

const User = () => {

  const router = useRouter();
  const {user_id} = router.query; 

  return (
    <div className={styles.User_body}>
      <Head>
        <title> {user_id} | Xetra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.User_wrapper}>User is pretty shit right now!</div>
    </div>
  );
};

export default User;
