import styles from "../../styles/user.module.css";
import Login from "../../components/Layout/Modal/Login";
import Head from "next/head";

const login = () => {
  return (
    <div className={styles.Auth_Main}>
      <Head>
        <title>Login | Xetra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
  );
};

export default login;
