import styles from "../../styles/user.module.css";
import Signup from "../../components/Layout/Modal/Signup";
import Head from "next/head";

const signup = () => {
  return (
    <div className={styles.Auth_Main}>
      <Head>
        <title>Signup | Xetra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Signup />
    </div>
  );
};

export default signup;
