import styles from "../../styles/products.module.css";
import Head from "next/head"
import Shop from "../../components/shop";
import { useEffect} from "react";
import { useDispatch, useSelector } from "react-redux"
import { getAllProducts } from "../../redux/actions/productAction";
import {useRouter} from "next/router"
import ProductModal from "../../components/Layout/ProductModal";
import ProductMain from "../../components/product/ProductMain";

const Products = () => {

  const dispatch = useDispatch();
  const {loading, error, products, productCount} = useSelector((state) => state.products);

  const router = useRouter();
  const {keyword, product_id, page} = router.query;

  useEffect(()=>{
    dispatch(getAllProducts(keyword || "",page || 1));
  },[dispatch,keyword,page])

  // useEffect(()=>{
  //   if(product_id) document.querySelector("body").style.setProperty("overflow","hidden");
  //   if(!product_id) document.querySelector("body").style.setProperty("overflow","");
  // },[product_id])

  return (
    <div className={styles.Products_body}>
      <Head>
        <title>Trending - Xetra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Shop loading={loading} error={error} products={products} productCount={productCount}/>
      {product_id && <ProductModal>
        <ProductMain product_id={product_id}/>
      </ProductModal>}
    </div>
  );
};

export default Products;
