import Head from 'next/head'
import Collections from '../components/Collections'
import Header from '../components/Header'
import ScrollTabs from '../components/ScrollTabs'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Xetra | Your Fashion One Stop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <ScrollTabs/>
      <Collections/>
    </div>
  )
}
