import Head from "next/head";
import { useRouter } from "next/router";
import Maintenance from "../../../components/Errors/Maintenance";
import styles from "./style.module.css";

const User = () => {

  const router = useRouter();
  const {user_id} = router.query; 

  return (
    <div className={styles.User_body}>
      <Head>
        <title> {user_id} | Xetra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Maintenance/>
    </div>
  );
};

export default User;
